// ISO 27001:2022 Annex A Controls
// Based on ISO/IEC 27001:2022 Information Security Management System

import type { RequirementData } from './soc2.js';

export const iso27001Requirements: RequirementData[] = [
  // A.5 - Organizational Controls
  {
    code: 'A.5',
    name: 'Organizational Controls',
    description: 'Controls related to organizational policies, roles, responsibilities, and information security management.',
    children: [
      {
        code: 'A.5.1',
        name: 'Policies for Information Security',
        description: 'Information security policy and topic-specific policies shall be defined, approved by management, published, communicated to and acknowledged by relevant personnel and relevant interested parties, and reviewed at planned intervals and if significant changes occur.',
        guidance: 'Develop an information security policy aligned with business objectives, communicate to all employees, and review periodically.',
      },
      {
        code: 'A.5.2',
        name: 'Information Security Roles and Responsibilities',
        description: 'Information security roles and responsibilities shall be defined and allocated according to the organization needs.',
        guidance: 'Define roles for CISO, security team, asset owners, and all personnel with security responsibilities.',
      },
      {
        code: 'A.5.3',
        name: 'Segregation of Duties',
        description: 'Conflicting duties and conflicting areas of responsibility shall be segregated.',
        guidance: 'Separate duties to reduce risk of fraud or error, especially for sensitive operations like financial transactions and system administration.',
      },
      {
        code: 'A.5.4',
        name: 'Management Responsibilities',
        description: 'Management shall require all personnel to apply information security in accordance with the established information security policy, topic-specific policies and procedures of the organization.',
        guidance: 'Ensure management enforces security policies and leads by example.',
      },
      {
        code: 'A.5.5',
        name: 'Contact with Authorities',
        description: 'The organization shall establish and maintain contact with relevant authorities.',
        guidance: 'Maintain relationships with law enforcement, regulators, and emergency services.',
      },
      {
        code: 'A.5.6',
        name: 'Contact with Special Interest Groups',
        description: 'The organization shall establish and maintain contact with special interest groups or other specialist security forums and professional associations.',
        guidance: 'Participate in ISACs, security forums, and professional associations for threat intelligence sharing.',
      },
      {
        code: 'A.5.7',
        name: 'Threat Intelligence',
        description: 'Information relating to information security threats shall be collected and analysed to produce threat intelligence.',
        guidance: 'Implement threat intelligence program to gather, analyze, and act on threat information.',
      },
      {
        code: 'A.5.8',
        name: 'Information Security in Project Management',
        description: 'Information security shall be integrated into project management.',
        guidance: 'Include security requirements in project planning, design, and implementation phases.',
      },
      {
        code: 'A.5.9',
        name: 'Inventory of Information and Other Associated Assets',
        description: 'An inventory of information and other associated assets, including owners, shall be developed and maintained.',
        guidance: 'Maintain comprehensive asset inventory including hardware, software, data, and services.',
      },
      {
        code: 'A.5.10',
        name: 'Acceptable Use of Information and Other Associated Assets',
        description: 'Rules for the acceptable use of information and other associated assets shall be identified, documented and implemented.',
        guidance: 'Define acceptable use policies for all organizational assets.',
      },
      {
        code: 'A.5.11',
        name: 'Return of Assets',
        description: 'Personnel and other interested parties as appropriate shall return all the organization\'s assets in their possession upon change or termination of their employment, contract or agreement.',
        guidance: 'Implement process to recover all assets when personnel leave the organization.',
      },
      {
        code: 'A.5.12',
        name: 'Classification of Information',
        description: 'Information shall be classified according to the information security needs of the organization based on confidentiality, integrity, availability and relevant interested party requirements.',
        guidance: 'Implement information classification scheme (e.g., Public, Internal, Confidential, Restricted).',
      },
      {
        code: 'A.5.13',
        name: 'Labelling of Information',
        description: 'An appropriate set of procedures for information labelling shall be developed and implemented in accordance with the information classification scheme adopted by the organization.',
        guidance: 'Label information assets according to classification, including electronic and physical labeling.',
      },
      {
        code: 'A.5.14',
        name: 'Information Transfer',
        description: 'Information transfer rules, procedures, or agreements shall be in place for all types of transfer facilities within the organization and between the organization and other parties.',
        guidance: 'Establish secure methods for transferring information internally and externally.',
      },
      {
        code: 'A.5.15',
        name: 'Access Control',
        description: 'Rules to control physical and logical access to information and other associated assets shall be established and implemented based on business and information security requirements.',
        guidance: 'Implement access control policy based on need-to-know and least privilege principles.',
      },
      {
        code: 'A.5.16',
        name: 'Identity Management',
        description: 'The full life cycle of identities shall be managed.',
        guidance: 'Manage identity lifecycle including provisioning, modification, and deprovisioning.',
      },
      {
        code: 'A.5.17',
        name: 'Authentication Information',
        description: 'Allocation and management of authentication information shall be controlled by a management process including advising personnel on appropriate handling of authentication information.',
        guidance: 'Implement strong password policies, MFA, and secure credential management.',
      },
      {
        code: 'A.5.18',
        name: 'Access Rights',
        description: 'Access rights to information and other associated assets shall be provisioned, reviewed, modified and removed in accordance with the organization\'s topic-specific policy on and rules for access control.',
        guidance: 'Implement access provisioning and regular access reviews.',
      },
      {
        code: 'A.5.19',
        name: 'Information Security in Supplier Relationships',
        description: 'Processes and procedures shall be defined and implemented to manage the information security risks associated with the use of supplier\'s products or services.',
        guidance: 'Assess and manage security risks from suppliers and third parties.',
      },
      {
        code: 'A.5.20',
        name: 'Addressing Information Security Within Supplier Agreements',
        description: 'Relevant information security requirements shall be established and agreed with each supplier based on the type of supplier relationship.',
        guidance: 'Include security requirements in supplier contracts and SLAs.',
      },
      {
        code: 'A.5.21',
        name: 'Managing Information Security in the ICT Supply Chain',
        description: 'Processes and procedures shall be defined and implemented to manage the information security risks associated with the ICT products and services supply chain.',
        guidance: 'Address supply chain security risks for ICT products and services.',
      },
      {
        code: 'A.5.22',
        name: 'Monitoring, Review and Change Management of Supplier Services',
        description: 'The organization shall regularly monitor, review, evaluate and manage change in supplier information security practices and service delivery.',
        guidance: 'Continuously monitor supplier compliance and manage changes to supplier relationships.',
      },
      {
        code: 'A.5.23',
        name: 'Information Security for Use of Cloud Services',
        description: 'Processes for acquisition, use, management and exit from cloud services shall be established in accordance with the organization\'s information security requirements.',
        guidance: 'Implement cloud security governance including due diligence, contractual requirements, and exit planning.',
      },
      {
        code: 'A.5.24',
        name: 'Information Security Incident Management Planning and Preparation',
        description: 'The organization shall plan and prepare for managing information security incidents by defining, establishing and communicating information security incident management processes, roles and responsibilities.',
        guidance: 'Develop incident response plan with defined roles, responsibilities, and procedures.',
      },
      {
        code: 'A.5.25',
        name: 'Assessment and Decision on Information Security Events',
        description: 'The organization shall assess information security events and decide if they are to be categorized as information security incidents.',
        guidance: 'Implement triage process to classify and prioritize security events.',
      },
      {
        code: 'A.5.26',
        name: 'Response to Information Security Incidents',
        description: 'Information security incidents shall be responded to in accordance with the documented procedures.',
        guidance: 'Execute incident response procedures including containment, eradication, and recovery.',
      },
      {
        code: 'A.5.27',
        name: 'Learning from Information Security Incidents',
        description: 'Knowledge gained from information security incidents shall be used to strengthen and improve the information security controls.',
        guidance: 'Conduct post-incident reviews and implement lessons learned.',
      },
      {
        code: 'A.5.28',
        name: 'Collection of Evidence',
        description: 'The organization shall establish and implement procedures for the identification, collection, acquisition and preservation of evidence related to information security events.',
        guidance: 'Implement forensic evidence collection and preservation procedures.',
      },
      {
        code: 'A.5.29',
        name: 'Information Security During Disruption',
        description: 'The organization shall plan how to maintain information security at an appropriate level during disruption.',
        guidance: 'Maintain security controls during business disruptions and disasters.',
      },
      {
        code: 'A.5.30',
        name: 'ICT Readiness for Business Continuity',
        description: 'ICT readiness shall be planned, implemented, maintained and tested based on business continuity objectives and ICT continuity requirements.',
        guidance: 'Ensure ICT systems support business continuity requirements.',
      },
      {
        code: 'A.5.31',
        name: 'Legal, Statutory, Regulatory and Contractual Requirements',
        description: 'Legal, statutory, regulatory and contractual requirements relevant to information security and the organization\'s approach to meet these requirements shall be identified, documented and kept up to date.',
        guidance: 'Maintain register of applicable legal and regulatory requirements.',
      },
      {
        code: 'A.5.32',
        name: 'Intellectual Property Rights',
        description: 'The organization shall implement appropriate procedures to protect intellectual property rights.',
        guidance: 'Implement controls to protect intellectual property including software licensing compliance.',
      },
      {
        code: 'A.5.33',
        name: 'Protection of Records',
        description: 'Records shall be protected from loss, destruction, falsification, unauthorized access and unauthorized release in accordance with legal, statutory, regulatory and contractual requirements.',
        guidance: 'Implement record retention and protection policies.',
      },
      {
        code: 'A.5.34',
        name: 'Privacy and Protection of PII',
        description: 'The organization shall identify and meet the requirements regarding the preservation of privacy and protection of PII according to applicable laws and regulations and contractual requirements.',
        guidance: 'Implement privacy program compliant with GDPR, CCPA, and other applicable regulations.',
      },
      {
        code: 'A.5.35',
        name: 'Independent Review of Information Security',
        description: 'The organization\'s approach to managing information security and its implementation including people, processes and technologies shall be reviewed independently at planned intervals, or when significant changes occur.',
        guidance: 'Conduct regular independent security audits and assessments.',
      },
      {
        code: 'A.5.36',
        name: 'Compliance with Policies, Rules and Standards for Information Security',
        description: 'Compliance with the organization\'s information security policy, topic-specific policies, rules and standards shall be regularly reviewed.',
        guidance: 'Monitor and enforce compliance with internal security policies.',
      },
      {
        code: 'A.5.37',
        name: 'Documented Operating Procedures',
        description: 'Operating procedures for information processing facilities shall be documented and made available to personnel who need them.',
        guidance: 'Document and maintain operational procedures for all critical systems.',
      },
    ],
  },
  // A.6 - People Controls
  {
    code: 'A.6',
    name: 'People Controls',
    description: 'Controls related to personnel security including screening, training, and disciplinary processes.',
    children: [
      {
        code: 'A.6.1',
        name: 'Screening',
        description: 'Background verification checks on all candidates to become personnel shall be carried out prior to joining the organization and on an ongoing basis taking into consideration applicable laws, regulations and ethics and be proportional to the business requirements, the classification of the information to be accessed and the perceived risks.',
        guidance: 'Conduct background checks appropriate to role sensitivity.',
      },
      {
        code: 'A.6.2',
        name: 'Terms and Conditions of Employment',
        description: 'The employment contractual agreements shall state the personnel\'s and the organization\'s responsibilities for information security.',
        guidance: 'Include security responsibilities in employment contracts.',
      },
      {
        code: 'A.6.3',
        name: 'Information Security Awareness, Education and Training',
        description: 'Personnel of the organization and relevant interested parties shall receive appropriate information security awareness, education and training and regular updates of the organization\'s information security policy, topic-specific policies and procedures, as relevant for their job function.',
        guidance: 'Implement comprehensive security awareness training program.',
      },
      {
        code: 'A.6.4',
        name: 'Disciplinary Process',
        description: 'A disciplinary process shall be formalized and communicated to take actions against personnel and other relevant interested parties who have committed an information security policy violation.',
        guidance: 'Define disciplinary procedures for security policy violations.',
      },
      {
        code: 'A.6.5',
        name: 'Responsibilities After Termination or Change of Employment',
        description: 'Information security responsibilities and duties that remain valid after termination or change of employment shall be defined, enforced and communicated to relevant personnel and other interested parties.',
        guidance: 'Define post-employment security obligations including NDAs.',
      },
      {
        code: 'A.6.6',
        name: 'Confidentiality or Non-Disclosure Agreements',
        description: 'Confidentiality or non-disclosure agreements reflecting the organization\'s needs for the protection of information shall be identified, documented, regularly reviewed and signed by personnel and other relevant interested parties.',
        guidance: 'Implement NDAs for employees, contractors, and third parties.',
      },
      {
        code: 'A.6.7',
        name: 'Remote Working',
        description: 'Security measures shall be implemented when personnel are working remotely to protect information accessed, processed or stored outside the organization\'s premises.',
        guidance: 'Implement remote work security policy covering devices, networks, and data protection.',
      },
      {
        code: 'A.6.8',
        name: 'Information Security Event Reporting',
        description: 'The organization shall provide a mechanism for personnel to report observed or suspected information security events through appropriate channels in a timely manner.',
        guidance: 'Establish clear reporting channels for security incidents.',
      },
    ],
  },
  // A.7 - Physical Controls
  {
    code: 'A.7',
    name: 'Physical Controls',
    description: 'Controls related to physical security including secure areas, equipment security, and environmental protection.',
    children: [
      {
        code: 'A.7.1',
        name: 'Physical Security Perimeters',
        description: 'Security perimeters shall be defined and used to protect areas that contain information and other associated assets.',
        guidance: 'Define and protect physical security boundaries for sensitive areas.',
      },
      {
        code: 'A.7.2',
        name: 'Physical Entry',
        description: 'Secure areas shall be protected by appropriate entry controls and access points.',
        guidance: 'Implement physical access controls such as card readers, biometrics, and visitor management.',
      },
      {
        code: 'A.7.3',
        name: 'Securing Offices, Rooms and Facilities',
        description: 'Physical security for offices, rooms and facilities shall be designed and implemented.',
        guidance: 'Design physical security appropriate to the sensitivity of assets.',
      },
      {
        code: 'A.7.4',
        name: 'Physical Security Monitoring',
        description: 'Premises shall be continuously monitored for unauthorized physical access.',
        guidance: 'Implement surveillance systems, alarms, and security monitoring.',
      },
      {
        code: 'A.7.5',
        name: 'Protecting Against Physical and Environmental Threats',
        description: 'Protection against physical and environmental threats, such as natural disasters and other intentional or unintentional physical threats to infrastructure shall be designed and implemented.',
        guidance: 'Implement environmental controls including fire suppression, flood protection, and climate control.',
      },
      {
        code: 'A.7.6',
        name: 'Working in Secure Areas',
        description: 'Security measures for working in secure areas shall be designed and implemented.',
        guidance: 'Define procedures for working in secure areas.',
      },
      {
        code: 'A.7.7',
        name: 'Clear Desk and Clear Screen',
        description: 'Clear desk rules for papers and removable storage media and clear screen rules for information processing facilities shall be defined and appropriately enforced.',
        guidance: 'Implement clear desk and clear screen policies.',
      },
      {
        code: 'A.7.8',
        name: 'Equipment Siting and Protection',
        description: 'Equipment shall be sited securely and protected.',
        guidance: 'Position and protect equipment to minimize environmental risks.',
      },
      {
        code: 'A.7.9',
        name: 'Security of Assets Off-Premises',
        description: 'Off-site assets shall be protected.',
        guidance: 'Implement controls for equipment used outside organizational premises.',
      },
      {
        code: 'A.7.10',
        name: 'Storage Media',
        description: 'Storage media shall be managed through their life cycle of acquisition, use, transportation and disposal in accordance with the organization\'s classification scheme and handling requirements.',
        guidance: 'Manage storage media lifecycle including secure disposal.',
      },
      {
        code: 'A.7.11',
        name: 'Supporting Utilities',
        description: 'Information processing facilities shall be protected from power failures and other disruptions caused by failures in supporting utilities.',
        guidance: 'Implement UPS, backup power, and redundant utilities.',
      },
      {
        code: 'A.7.12',
        name: 'Cabling Security',
        description: 'Cables carrying power, data or supporting information services shall be protected from interception, interference or damage.',
        guidance: 'Protect network and power cabling from tampering.',
      },
      {
        code: 'A.7.13',
        name: 'Equipment Maintenance',
        description: 'Equipment shall be maintained correctly to ensure availability, integrity and confidentiality of information.',
        guidance: 'Implement equipment maintenance program.',
      },
      {
        code: 'A.7.14',
        name: 'Secure Disposal or Re-Use of Equipment',
        description: 'Items of equipment containing storage media shall be verified to ensure that any sensitive data and licensed software has been removed or securely overwritten prior to disposal or re-use.',
        guidance: 'Implement secure media sanitization procedures.',
      },
    ],
  },
  // A.8 - Technological Controls
  {
    code: 'A.8',
    name: 'Technological Controls',
    description: 'Controls related to technology including endpoint security, access management, cryptography, and secure development.',
    children: [
      {
        code: 'A.8.1',
        name: 'User Endpoint Devices',
        description: 'Information stored on, processed by or accessible via user endpoint devices shall be protected.',
        guidance: 'Implement endpoint security including encryption, MDM, and security software.',
      },
      {
        code: 'A.8.2',
        name: 'Privileged Access Rights',
        description: 'The allocation and use of privileged access rights shall be restricted and managed.',
        guidance: 'Implement privileged access management with just-in-time access and monitoring.',
      },
      {
        code: 'A.8.3',
        name: 'Information Access Restriction',
        description: 'Access to information and other associated assets shall be restricted in accordance with the established topic-specific policy on access control.',
        guidance: 'Implement access controls based on classification and need-to-know.',
      },
      {
        code: 'A.8.4',
        name: 'Access to Source Code',
        description: 'Read and write access to source code, development tools and software libraries shall be appropriately managed.',
        guidance: 'Implement source code access controls and version control.',
      },
      {
        code: 'A.8.5',
        name: 'Secure Authentication',
        description: 'Secure authentication technologies and procedures shall be implemented based on information access restrictions and the topic-specific policy on access control.',
        guidance: 'Implement MFA, SSO, and strong authentication mechanisms.',
      },
      {
        code: 'A.8.6',
        name: 'Capacity Management',
        description: 'The use of resources shall be monitored and adjusted in line with current and expected capacity requirements.',
        guidance: 'Monitor and plan for capacity requirements.',
      },
      {
        code: 'A.8.7',
        name: 'Protection Against Malware',
        description: 'Protection against malware shall be implemented and supported by appropriate user awareness.',
        guidance: 'Implement anti-malware controls including EDR, email filtering, and user training.',
      },
      {
        code: 'A.8.8',
        name: 'Management of Technical Vulnerabilities',
        description: 'Information about technical vulnerabilities of information systems in use shall be obtained, the organization\'s exposure to such vulnerabilities shall be evaluated and appropriate measures shall be taken.',
        guidance: 'Implement vulnerability management program including scanning and patching.',
      },
      {
        code: 'A.8.9',
        name: 'Configuration Management',
        description: 'Configurations, including security configurations, of hardware, software, services and networks shall be established, documented, implemented, monitored and reviewed.',
        guidance: 'Implement configuration management and hardening standards.',
      },
      {
        code: 'A.8.10',
        name: 'Information Deletion',
        description: 'Information stored in information systems, devices or in any other storage media shall be deleted when no longer required.',
        guidance: 'Implement data retention and secure deletion procedures.',
      },
      {
        code: 'A.8.11',
        name: 'Data Masking',
        description: 'Data masking shall be used in accordance with the organization\'s topic-specific policy on access control and other related topic-specific policies, and business requirements, taking applicable legislation into consideration.',
        guidance: 'Implement data masking for sensitive data in non-production environments.',
      },
      {
        code: 'A.8.12',
        name: 'Data Leakage Prevention',
        description: 'Data leakage prevention measures shall be applied to systems, networks and any other devices that process, store or transmit sensitive information.',
        guidance: 'Implement DLP controls for sensitive data protection.',
      },
      {
        code: 'A.8.13',
        name: 'Information Backup',
        description: 'Backup copies of information, software and systems shall be maintained and regularly tested in accordance with the agreed topic-specific policy on backup.',
        guidance: 'Implement backup strategy with regular testing of restore procedures.',
      },
      {
        code: 'A.8.14',
        name: 'Redundancy of Information Processing Facilities',
        description: 'Information processing facilities shall be implemented with redundancy sufficient to meet availability requirements.',
        guidance: 'Implement high availability and redundancy for critical systems.',
      },
      {
        code: 'A.8.15',
        name: 'Logging',
        description: 'Logs that record activities, exceptions, faults and other relevant events shall be produced, stored, protected and analysed.',
        guidance: 'Implement comprehensive logging and log management.',
      },
      {
        code: 'A.8.16',
        name: 'Monitoring Activities',
        description: 'Networks, systems and applications shall be monitored for anomalous behaviour and appropriate actions taken to evaluate potential information security incidents.',
        guidance: 'Implement security monitoring and SIEM.',
      },
      {
        code: 'A.8.17',
        name: 'Clock Synchronization',
        description: 'The clocks of information processing systems used by the organization shall be synchronized to approved time sources.',
        guidance: 'Implement NTP synchronization across all systems.',
      },
      {
        code: 'A.8.18',
        name: 'Use of Privileged Utility Programs',
        description: 'The use of utility programs that might be capable of overriding system and application controls shall be restricted and tightly controlled.',
        guidance: 'Control access to and use of privileged utility programs.',
      },
      {
        code: 'A.8.19',
        name: 'Installation of Software on Operational Systems',
        description: 'Procedures and measures shall be implemented to securely manage software installation on operational systems.',
        guidance: 'Control software installation through application whitelisting or approval processes.',
      },
      {
        code: 'A.8.20',
        name: 'Networks Security',
        description: 'Networks and network devices shall be secured, managed and controlled to protect information in systems and applications.',
        guidance: 'Implement network security controls including segmentation, firewalls, and monitoring.',
      },
      {
        code: 'A.8.21',
        name: 'Security of Network Services',
        description: 'Security mechanisms, service levels and service requirements of network services shall be identified, implemented and monitored.',
        guidance: 'Define and monitor security requirements for network services.',
      },
      {
        code: 'A.8.22',
        name: 'Segregation of Networks',
        description: 'Groups of information services, users and information systems shall be segregated in the organization\'s networks.',
        guidance: 'Implement network segmentation based on security requirements.',
      },
      {
        code: 'A.8.23',
        name: 'Web Filtering',
        description: 'Access to external websites shall be managed to reduce exposure to malicious content.',
        guidance: 'Implement web filtering to block malicious and inappropriate content.',
      },
      {
        code: 'A.8.24',
        name: 'Use of Cryptography',
        description: 'Rules for the effective use of cryptography, including cryptographic key management, shall be defined and implemented.',
        guidance: 'Implement cryptographic controls including key management.',
      },
      {
        code: 'A.8.25',
        name: 'Secure Development Life Cycle',
        description: 'Rules for the secure development of software and systems shall be established and applied.',
        guidance: 'Implement SDLC security including security requirements, design reviews, and testing.',
      },
      {
        code: 'A.8.26',
        name: 'Application Security Requirements',
        description: 'Information security requirements shall be identified, specified and approved when developing or acquiring applications.',
        guidance: 'Define security requirements for application development and acquisition.',
      },
      {
        code: 'A.8.27',
        name: 'Secure System Architecture and Engineering Principles',
        description: 'Principles for engineering secure systems shall be established, documented, maintained and applied to any information system development activities.',
        guidance: 'Apply security architecture principles including defense in depth.',
      },
      {
        code: 'A.8.28',
        name: 'Secure Coding',
        description: 'Secure coding principles shall be applied to software development.',
        guidance: 'Implement secure coding practices and guidelines.',
      },
      {
        code: 'A.8.29',
        name: 'Security Testing in Development and Acceptance',
        description: 'Security testing processes shall be defined and implemented in the development life cycle.',
        guidance: 'Implement security testing including SAST, DAST, and penetration testing.',
      },
      {
        code: 'A.8.30',
        name: 'Outsourced Development',
        description: 'The organization shall direct, monitor and review the activities related to outsourced system development.',
        guidance: 'Manage security of outsourced development activities.',
      },
      {
        code: 'A.8.31',
        name: 'Separation of Development, Test and Production Environments',
        description: 'Development, testing and production environments shall be separated and secured.',
        guidance: 'Maintain separate environments for development, testing, and production.',
      },
      {
        code: 'A.8.32',
        name: 'Change Management',
        description: 'Changes to information processing facilities and information systems shall be subject to change management procedures.',
        guidance: 'Implement change management process for all system changes.',
      },
      {
        code: 'A.8.33',
        name: 'Test Information',
        description: 'Test information shall be appropriately selected, protected and managed.',
        guidance: 'Protect test data, avoid using production data in testing without anonymization.',
      },
      {
        code: 'A.8.34',
        name: 'Protection of Information Systems During Audit Testing',
        description: 'Audit tests and other assurance activities involving assessment of operational systems shall be planned and agreed between the tester and appropriate management.',
        guidance: 'Control audit activities to minimize impact on production systems.',
      },
    ],
  },
];
