import type { IntegrationType, EvidenceType } from '@lightsail/shared';

/**
 * Result from connecting to an integration provider.
 */
export interface ConnectionResult {
  success: boolean;
  error?: string;
  /** Provider-specific metadata (e.g., authenticated user, org name) */
  metadata?: Record<string, unknown>;
}

/**
 * Result from testing an integration connection.
 */
export interface TestResult {
  success: boolean;
  latencyMs: number;
  error?: string;
  /** Scopes/permissions available with current credentials */
  scopes?: string[];
}

/**
 * Error from data collection.
 */
export interface CollectionError {
  code: string;
  message: string;
  /** Whether this error is likely to succeed on retry */
  retryable: boolean;
  /** Additional context */
  context?: Record<string, unknown>;
}

/**
 * Result from a single collector (e.g., repos, branch-protection).
 */
export interface CollectionResult {
  success: boolean;
  /** Collector name (e.g., 'repos', 'iam-users', 'branch-protection') */
  collector: string;
  /** Number of items collected */
  itemsCollected: number;
  /** Errors encountered during collection */
  errors: CollectionError[];
  /** Raw data from the provider (stored in evidence metadata) */
  rawData: unknown;
  /** When this collection occurred */
  collectedAt: Date;
}

/**
 * Verification result from evidence analysis.
 * Indicates whether the evidence shows the control is properly implemented.
 */
export interface EvidenceVerificationResult {
  /** Whether the control appears to be implemented based on evidence */
  isImplemented: boolean;
  /** Confidence level: 'high' for clear pass/fail, 'medium' for partial, 'low' for inconclusive */
  confidence: 'high' | 'medium' | 'low';
  /** Human-readable reason for the result */
  reason: string;
  /** Specific metrics that led to this conclusion */
  metrics?: Record<string, unknown>;
}

/**
 * Evidence ready to be stored in the database.
 * Generated by providers from raw collection data.
 */
export interface GeneratedEvidence {
  title: string;
  description: string;
  type: EvidenceType;
  /** Source identifier (e.g., 'github', 'aws-iam', 'google-workspace') */
  source: string;
  /** Structured data about what was collected */
  metadata: Record<string, unknown>;
  /** When the evidence becomes valid */
  validFrom: Date;
  /** When the evidence expires (typically 24h for automated collection) */
  validUntil: Date;
  /**
   * Patterns to match controls for auto-linking.
   * Matched against control names, codes, and tags.
   */
  controlPatterns?: string[];
  /**
   * Verification result from analyzing the evidence.
   * Used to auto-set control implementation status.
   */
  verificationResult?: EvidenceVerificationResult;
}

/**
 * Mapping between evidence source and controls.
 * Used to auto-link generated evidence to relevant controls.
 */
export interface ControlMapping {
  /** Evidence source to match (e.g., 'github-repos') */
  evidenceSource: string;
  /** Regex pattern to match control names */
  controlNamePattern?: RegExp;
  /** Regex pattern to match control codes */
  controlCodePattern?: RegExp;
  /** Tags to match on controls */
  controlTags?: string[];
}

/**
 * Configuration for creating a provider instance.
 */
export interface IntegrationProviderConfig {
  organizationId: string;
  integrationId: string;
  credentials: Record<string, unknown>;
  config: Record<string, unknown>;
}

/**
 * Sync job status.
 */
export type SyncJobStatus = 'pending' | 'running' | 'completed' | 'failed';

/**
 * A sync job being executed or queued.
 */
export interface SyncJob {
  id: string;
  integrationId: string;
  organizationId: string;
  status: SyncJobStatus;
  /** Which collectors to run (empty = all) */
  collectors: string[];
  startedAt?: Date;
  completedAt?: Date;
  result?: SyncResult;
  error?: string;
}

/**
 * Result from a completed sync operation.
 */
export interface SyncResult {
  /** Number of evidence records created */
  evidenceGenerated: number;
  /** Number of controls updated (verification status) */
  controlsVerified: number;
  /** Number of controls that failed verification */
  controlsFailed: number;
  /** Errors encountered during sync */
  errors: CollectionError[];
  /** Total sync duration in milliseconds */
  durationMs: number;
}

/**
 * Information about an available collector.
 */
export interface CollectorInfo {
  /** Collector ID (e.g., 'repos', 'branch-protection') */
  id: string;
  /** Human-readable name */
  name: string;
  /** What this collector gathers */
  description: string;
  /** Evidence types this collector generates */
  evidenceTypes: EvidenceType[];
  /** Control categories this collector helps verify */
  controlCategories: string[];
}

/**
 * Information about an integration type.
 */
export interface IntegrationTypeInfo {
  type: IntegrationType;
  displayName: string;
  description: string;
  /** Icon identifier for frontend */
  icon: string;
  /** Required credential fields */
  requiredCredentials: CredentialField[];
  /** Optional configuration fields */
  configFields: ConfigField[];
  /** Available collectors */
  collectors: CollectorInfo[];
}

/**
 * Definition of a credential field.
 */
export interface CredentialField {
  key: string;
  label: string;
  type: 'text' | 'password' | 'textarea';
  placeholder?: string;
  helpText?: string;
  required: boolean;
}

/**
 * Definition of a configuration field.
 */
export interface ConfigField {
  key: string;
  label: string;
  type: 'text' | 'number' | 'boolean' | 'select';
  options?: { value: string; label: string }[];
  defaultValue?: unknown;
  helpText?: string;
}
